name: CI Build and Docker Push

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Hello Spring K8S
        working-directory: ./hello-spring-k8s
        run: ./mvnw clean package -DskipTests

      - name: Build Hello Caller
        working-directory: ./hello-caller
        run: ./mvnw clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Hello Spring K8S Image
        uses: docker/build-push-action@v5
        with:
          context: ./hello-spring-k8s
          file: ./hello-spring-k8s/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-spring-k8s:latest

      - name: Build and Push Hello Caller Image
        uses: docker/build-push-action@v5
        with:
          context: ./hello-caller
          file: ./hello-caller/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-caller:latest
